# Generated by Django 5.1 on 2024-09-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
