# Generated by Django 5.1 on 2024-09-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_data',
            field=models.ImageField(upload_to=''),
        ),
    ]
