# Generated by Django 5.1 on 2024-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_carimage_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_data',
            field=models.ImageField(upload_to='car_images/'),
        ),
    ]
