# Generated by Django 5.1 on 2024-09-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_carimage_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='query',
            name='response_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
