# Generated by Django 5.1 on 2024-09-26 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction_payment_id_transaction_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.car'),
        ),
    ]
