# Generated by Django 5.1 on 2024-09-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transaction_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
